# Generated by Django 4.2.20 on 2025-04-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myevol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-end_date'], 'verbose_name': 'Défi', 'verbose_name_plural': 'Défis'},
        ),
        migrations.AlterModelOptions(
            name='journalmedia',
            options={'ordering': ['created_at'], 'verbose_name': 'Média', 'verbose_name_plural': 'Médias'},
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='animation_url',
            field=models.URLField(blank=True, help_text="Lien vers une animation Lottie ou GIF pour enrichir l'affichage du badge", null=True),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='color_theme',
            field=models.CharField(default='#FFD700', max_length=20),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="Lien vers l'image de l'avatar", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text="Points d'expérience cumulés"),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mood_tag',
            field=models.CharField(blank=True, help_text="Étiquette d'humeur associée (ex: 'positive', 'low', 'neutral')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', 'action'], name='Myevol_app__user_id_e0f943_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['created_at'], name='Myevol_app__created_20eb22_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['mood_tag'], name='Myevol_app__mood_ta_ef3048_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['author'], name='Myevol_app__author_3a2bb3_idx'),
        ),
    ]
