# Generated by Django 4.2.20 on 2025-04-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myevol_app', '0002_alter_challenge_options_alter_journalmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgetemplate',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Modèle de badge', 'verbose_name_plural': 'Modèles de badges'},
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Détermine si le badge peut être attribué'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='date_obtenue',
            field=models.DateField(auto_now_add=True, help_text="Date d'obtention automatique du badge"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(help_text='Texte descriptif affiché dans l’application'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(help_text="Icône du badge (emoji ou chemin d'image)", max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Niveau associé (pour les badges de progression)', null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Nom du badge (ex. Niveau 3, Régulier)', max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur ayant obtenu ce badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='animation_url',
            field=models.URLField(blank=True, help_text='Animation Lottie ou GIF du badge', null=True),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='color_theme',
            field=models.CharField(default='#FFD700', help_text="Couleur d'affichage du badge", max_length=20),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='condition',
            field=models.CharField(help_text='Description simple de la condition d’obtention', max_length=255),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='description',
            field=models.TextField(help_text="Description visible dans l'app"),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='icon',
            field=models.CharField(help_text='Icône (emoji, URL ou nom de fichier)', max_length=100),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text="Niveau cible pour les badges de type 'Niveau'", null=True),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='name',
            field=models.CharField(help_text='Nom unique du badge (ex. Régulier, Niveau 3)', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['user', 'name'], name='Myevol_app__user_id_1656ff_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['user', 'date_obtenue'], name='Myevol_app__user_id_5eee4a_idx'),
        ),
    ]
