# Generated by Django 4.2.20 on 2025-04-21 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myevol_app', '0003_alter_badgetemplate_options_badgetemplate_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeprogress',
            options={'verbose_name': 'Progression de défi', 'verbose_name_plural': 'Progressions de défis'},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='Description détaillée du défi'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(help_text='Date de fin du défi (inclus)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(help_text='Date de début du défi (inclus)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_entries',
            field=models.PositiveIntegerField(default=5, help_text="Nombre d'entrées attendues pour réussir le défi"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(help_text='Titre du défi visible par les utilisateurs', max_length=255),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='challenge',
            field=models.ForeignKey(help_text='Défi concerné', on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='Myevol_app.challenge'),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indique si le défi a été complété par l’utilisateur'),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date de complétion du défi (si terminé)', null=True),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur participant au défi', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
