# Generated by Django 4.2.20 on 2025-04-21 10:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myevol_app', '0004_alter_challengeprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgetemplate',
            options={'verbose_name': 'Modèle de badge', 'verbose_name_plural': 'Modèles de badges'},
        ),
        migrations.AlterModelOptions(
            name='challengeprogress',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='badge',
            name='Myevol_app__user_id_1656ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='badge',
            name='Myevol_app__user_id_5eee4a_idx',
        ),
        migrations.RemoveField(
            model_name='badgetemplate',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='badge',
            name='date_obtenue',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='animation_url',
            field=models.URLField(blank=True, help_text="Lien vers une animation Lottie ou GIF pour enrichir l'affichage du badge", null=True),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='color_theme',
            field=models.CharField(default='#FFD700', max_length=20),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='Objectif et règles du défi'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(help_text='Date de fin du défi'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(help_text='Date de début du défi'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_entries',
            field=models.PositiveIntegerField(default=5, help_text='Nombre d’entrées à atteindre pour réussir ce défi'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(help_text='Titre du défi (affiché dans l’interface)', max_length=255),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='Myevol_app.challenge'),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='category',
            field=models.CharField(help_text="Thématique de l'entrée (ex: Travail, Perso, Sport).", max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(help_text='Texte libre décrivant votre journée ou vos accomplissements.', verbose_name="Qu'avez-vous accompli aujourd'hui ?"),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de création de l'entrée."),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], help_text='Note d’humeur de 1 à 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Note d'humeur"),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="Date de dernière modification de l'entrée."),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(help_text="Utilisateur ayant rédigé l'entrée.", on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du fichier."),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='entry',
            field=models.ForeignKey(help_text='Entrée de journal associée à ce média.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Myevol_app.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='file',
            field=models.FileField(help_text='Fichier média (image ou audio).', upload_to='journal_media/'),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], help_text='Type de média.', max_length=10),
        ),
    ]
