# Generated by Django 4.2.20 on 2025-04-21 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myevol_app', '0005_alter_badgetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(verbose_name="Qu'avez-vous accompli aujourd'hui ?"),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name="Note d'humeur"),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Myevol_app.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='file',
            field=models.FileField(upload_to='journal_media/'),
        ),
        migrations.AlterField(
            model_name='journalmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=10),
        ),
    ]
