"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k%s35+y)-2%f2sft$2et#0$=6yt)q_)uxyb14x$+@jfzqf5fi)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Myevol_app',
    'django_celery_beat',
    'rest_framework',
    'corsheaders',  # pour autoriser l'accès depuis Expo
    'rest_framework_simplejwt',
    'rest_framework.authtoken',  # seulement si tu veux aussi gérer des tokens classiques




]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True  # à restreindre en prod
CORS_ALLOW_CREDENTIALS = True  # pour les cookies d'authentification

ROOT_URLCONF = 'config.urls'


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



import os
from dotenv import load_dotenv

# Charge les variables depuis le fichier .env
load_dotenv()

# Configuration de la base de données
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_TZ = True
USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Myevol_app.User'

LOGIN_URL = 'myevol:login'
LOGIN_REDIRECT_URL = 'myevol:dashboard'
LOGOUT_REDIRECT_URL = 'myevol:login'

# CELERY CONFIG
CELERY_BROKER_URL = "redis://localhost:6379/0"  # Assure-toi que Redis tourne
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'

from datetime import timedelta

CELERY_BEAT_SCHEDULE = {
    # 🔔 Envoyer la question "Qu'as-tu fait aujourd'hui ?" tous les jours à 19h
    'ask_user_daily_activity': {
        'task': 'Myevol_app.tasks.ask_user_daily_activity',
        'schedule': crontab(hour=19, minute=0),
    },

    # 📊 Générer statistiques journalières tous les jours à minuit
    'generate_daily_stats': {
        'task': 'Myevol_app.tasks.generate_all_daily_stats',
        'schedule': crontab(hour=0, minute=0),
    },

    # 📈 Générer statistiques hebdomadaires chaque lundi à 9h
    'generate_weekly_stats': {
        'task': 'Myevol_app.tasks.generate_all_weekly_stats',
        'schedule': crontab(hour=9, minute=0, day_of_week=1),  # 1 = lundi
    },

    # 📅 Générer statistiques mensuelles le 1er du mois à 9h
    'generate_monthly_stats': {
        'task': 'Myevol_app.tasks.generate_all_monthly_stats',
        'schedule': crontab(hour=9, minute=0, day_of_month=1),
    },

    # 🗓️ Générer statistiques annuelles le 1er janvier à 9h
    'generate_annual_stats': {
        'task': 'Myevol_app.tasks.generate_all_annual_stats',
        'schedule': crontab(hour=9, minute=0, day_of_month=1, month_of_year=1),
    },

    # 🧹 Nettoyer les anciennes notifications (> 90 jours) tous les jours à 3h du matin
    'clean_old_notifications': {
        'task': 'Myevol_app.tasks.clean_old_notifications',
        'schedule': crontab(hour=3, minute=0),
    },

    # 🧠 Vérifier/Recalculer les streaks tous les jours à 0h30
    'update_user_streaks': {
        'task': 'Myevol_app.tasks.recalculate_all_streaks',
        'schedule': crontab(hour=0, minute=30),
    },

    # 🚨 Envoyer un rappel s’il n’y a pas eu d'entrée depuis X jours (ex: tous les jours à 18h)
    'remind_inactive_users': {
        'task': 'Myevol_app.tasks.remind_inactive_users',
        'schedule': crontab(hour=18, minute=0),
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Par exemple 10 badges par page
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MyEvol API',
    'DESCRIPTION': "Documentation complète de l'API MyEvol pour l'application mobile et web.",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Ajouts recommandés
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
    'CONTACT': {'name': 'Équipe MyEvol', 'email': 'support@myevol.app'},
    'LICENSE': {'name': 'Propriétaire'},
    'TAGS': [
        {'name': 'Journal', 'description': 'Entrées de journal et médias associés'},
        {'name': 'Objectifs', 'description': 'Objectifs personnels à atteindre'},
        {'name': 'Badges', 'description': 'Système de récompenses et de progression'},
        {'name': 'Statistiques', 'description': 'Analyses de données et tendances'},
        {'name': 'Utilisateurs', 'description': 'Gestion des comptes et préférences'},
        {'name': 'Notifications', 'description': 'Système de notifications'},
        {'name': 'Challenges', 'description': 'Défis et compétitions'},
    ],
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',  # ou INFO
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
DEFAULT_ADMIN_EMAIL = "admin@monapp.com"
